# Generated by Django 5.0.4 on 2024-05-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='id',
        ),
        migrations.AlterField(
            model_name='admin',
            name='e_mail',
            field=models.EmailField(max_length=60),
        ),
        migrations.AlterField(
            model_name='admin',
            name='register',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='e_mail',
            field=models.EmailField(max_length=60),
        ),
    ]
