# Generated by Django 5.0.4 on 2024-05-08 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentloans',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
