# Generated by Django 5.0.4 on 2024-05-08 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0003_alter_studentloans_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentloans',
            name='loan_0',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_0', to='modelo.loan'),
        ),
        migrations.AlterField(
            model_name='studentloans',
            name='loan_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_1', to='modelo.loan'),
        ),
        migrations.AlterField(
            model_name='studentloans',
            name='loan_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_2', to='modelo.loan'),
        ),
        migrations.AlterField(
            model_name='studentloans',
            name='loan_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_3', to='modelo.loan'),
        ),
        migrations.AlterField(
            model_name='studentloans',
            name='loan_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_4', to='modelo.loan'),
        ),
        migrations.AlterField(
            model_name='studentloans',
            name='loan_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_5', to='modelo.loan'),
        ),
        migrations.AlterField(
            model_name='studentloans',
            name='loan_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_6', to='modelo.loan'),
        ),
        migrations.AlterField(
            model_name='studentloans',
            name='loan_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_7', to='modelo.loan'),
        ),
        migrations.AlterField(
            model_name='studentloans',
            name='loan_8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_8', to='modelo.loan'),
        ),
        migrations.AlterField(
            model_name='studentloans',
            name='loan_9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_9', to='modelo.loan'),
        ),
    ]
