# Generated by Django 5.0.4 on 2024-05-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0005_alter_student_loans'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='token',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='token',
            field=models.CharField(default='asdasdasd', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
